### ISSUE TITLE
When updating a BUILD file, the aspect cache needs to be flushed for all downstream projects

### ISSUE THREAD

**Issue by simontoens** [salesforce/bazel-eclipse#201]
Since each aspect tracks the transitive closure of dependencies, updating an upstream BUILD file (and modifying dependencies) requires the aspect cache flushing for all downstream projects.  General area where the fix needs to go: 

https://github.com/salesforce/bazel-eclipse/blob/9d73e8dc362740ca03d5dc370826450e4f51b17a/plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerInitializer.java#L167

One manifestation of this bug is this error when a project is re-imported:
```
[com.salesforce.bazel.sdk.command.internal.BazelWorkspaceAspectHelper] ASPECT CACHE PUT target: //projects/libs/scone/abstractions:src/test/java/com/salesforce/sconems/config/EnvironmentPropertiesTest [target=//projects/libs/scone/abstractions:src/test/java/com/salesforce/sconems/config/EnvironmentPropertiesTest, src=importWorkspace]
java.lang.RuntimeException: java.lang.IllegalStateException: Did not expect a duplicate label with different contents: //projects/libs/scone/abstractions:abstractions
	at com.salesforce.bazel.eclipse.projectimport.flow.LoadAspectsFlow.run(LoadAspectsFlow.java:78)
	at com.salesforce.bazel.eclipse.projectimport.flow.FlowProjectImporter.runFlows(FlowProjectImporter.java:82)
	at com.salesforce.bazel.eclipse.projectimport.flow.FlowProjectImporter.run(FlowProjectImporter.java:70)
	at com.salesforce.bazel.eclipse.wizard.BazelProjectImporter$1.run(BazelProjectImporter.java:33)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.IllegalStateException: Did not expect a duplicate label with different contents: //projects/libs/scone/abstractions:abstractions
	at com.salesforce.bazel.sdk.aspect.AspectTargetInfos.<init>(AspectTargetInfos.java:70)
	at com.salesforce.bazel.eclipse.projectimport.flow.LoadAspectsFlow.run(LoadAspectsFlow.java:76)
	... 4 more
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Did not expect a duplicate label with different contents: //projects/libs/scone/abstractions:abstractions
	at com.salesforce.bazel.eclipse.projectimport.flow.FlowProjectImporter.runFlows(FlowProjectImporter.java:89)
	at com.salesforce.bazel.eclipse.projectimport.flow.FlowProjectImporter.run(FlowProjectImporter.java:70)
	at com.salesforce.bazel.eclipse.wizard.BazelProjectImporter$1.run(BazelProjectImporter.java:33)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Did not expect a duplicate label with different contents: //projects/libs/scone/abstractions:abstractions
	at com.salesforce.bazel.eclipse.projectimport.flow.LoadAspectsFlow.run(LoadAspectsFlow.java:78)
	at com.salesforce.bazel.eclipse.projectimport.flow.FlowProjectImporter.runFlows(FlowProjectImporter.java:82)
	... 3 more
Caused by: java.lang.IllegalStateException: Did not expect a duplicate label with different contents: //projects/libs/scone/abstractions:abstractions
	at com.salesforce.bazel.sdk.aspect.AspectTargetInfos.<init>(AspectTargetInfos.java:70)
	at com.salesforce.bazel.eclipse.projectimport.flow.LoadAspectsFlow.run(LoadAspectsFlow.java:76)
	... 4 more

```

**Comment by plaird** [comment]
In the meantime, users can use Eclipse's _Clean_ to force regen of the aspect manually.
