### ISSUE TITLE
Class ch.qos.logback.classic.LoggerContext does not implement the requested interface org.slf4j.ILoggerFactory

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#35]
Creating a distinct issue from Issue #10 even though they are tracking similar issues, to make this bug more visible to new users. It is a benign exception but seems to be common when installing from updatesite .zip file.

Root exception:
java.lang.IncompatibleClassChangeError: Class ch.qos.logback.classic.LoggerContext does not implement the requested interface org.slf4j.ILoggerFactory
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at com.gradleware.tooling.toolingclient.internal.DefaultToolingClient.<clinit>(DefaultToolingClient.java:38)
	at com.gradleware.tooling.toolingclient.ToolingClient.newClient(ToolingClient.java:41)
	at org.eclipse.buildship.core.CorePlugin.createToolingClient(CorePlugin.java:190)
	at org.eclipse.buildship.core.CorePlugin.registerServices(CorePlugin.java:154)
	at org.eclipse.buildship.core.CorePlugin.start(CorePlugin.java:117)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:782)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:775)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:732)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	at org.eclipse.osgi.container.Module.doStart(Module.java:584)
	at org.eclipse.osgi.container.Module.start(Module.java:452)

**Comment by plaird** [comment]
I created a temporary fix by ripping out external logging libs from BEF. I will leave the root issue #10 open for further investigation.

https://github.com/salesforce/bazel-eclipse/commit/0da5fafeb72a27060986546e5a84ec6ed310f5c2
