### ISSUE TITLE
UI Freeze due to heavy logging in UI thread while resolving classpath

### ISSUE THREAD

**Issue by guw** [salesforce/bazel-eclipse#440]
I noticed a couple of UI freezes in my Eclipse instances. Turns out that BEF is doing expensive logging within the UI thread.

```
Stack Trace
	at java.base@17.0.5/java.lang.Throwable.fillInStackTrace(Native Method)
	at java.base@17.0.5/java.lang.Throwable.fillInStackTrace(Throwable.java:798)
	at java.base@17.0.5/java.lang.Throwable.<init>(Throwable.java:256)
	at java.base@17.0.5/java.lang.Exception.<init>(Exception.java:55)
	at java.base@17.0.5/java.lang.Thread.getStackTrace(Thread.java:1610)
	at org.eclipse.osgi.internal.log.LoggerImpl.getLocation(LoggerImpl.java:304)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:88)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:80)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:76)
	at org.eclipse.core.internal.runtime.Log.log(Log.java:68)
	at com.salesforce.bazel.eclipse.logging.EclipseLoggerFacade.writeLog(EclipseLoggerFacade.java:187)
	at com.salesforce.bazel.eclipse.logging.EclipseLoggerFacade.writeLog(EclipseLoggerFacade.java:176)
	at com.salesforce.bazel.eclipse.logging.EclipseLoggerFacade.info(EclipseLoggerFacade.java:167)
	at com.salesforce.bazel.sdk.logging.LoggerFacade.log(LoggerFacade.java:89)
	at com.salesforce.bazel.sdk.logging.LogHelper.info(LogHelper.java:112)
	at com.salesforce.bazel.eclipse.runtime.impl.EclipseResourceHelper.findMemberInWorkspace(EclipseResourceHelper.java:184)
	at com.salesforce.bazel.eclipse.utils.EclipseProjectSettingsUtils.checkProject(EclipseProjectSettingsUtils.java:81)
	at com.salesforce.bazel.eclipse.utils.EclipseProjectSettingsUtils.getOwningProjectForSourcePath(EclipseProjectSettingsUtils.java:58)
	at com.salesforce.bazel.eclipse.config.AbstractBazelProjectManager.getOwningProjectForSourcePath(AbstractBazelProjectManager.java:62)
	at com.salesforce.bazel.sdk.lang.jvm.BazelJvmClasspath.getSourceProjectForSourcePaths(BazelJvmClasspath.java:357)
	at com.salesforce.bazel.sdk.lang.jvm.BazelJvmClasspath.getClasspathEntries(BazelJvmClasspath.java:217)
	at com.salesforce.bazel.eclipse.classpath.BazelClasspathContainer.computeClasspath(BazelClasspathContainer.java:140)
	at com.salesforce.bazel.eclipse.classpath.BaseBazelClasspathContainer.getClasspathEntries(BaseBazelClasspathContainer.java:135)
	at com.salesforce.bazel.eclipse.classpath.BazelClasspathContainer.getClasspathEntries(BazelClasspathContainer.java:124)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3277)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3194)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3182)
	at org.eclipse.jdt.internal.core.JavaProject.findPackageFragmentRoots(JavaProject.java:1661)
	at org.eclipse.jdt.internal.ui.packageview.ClassPathContainer.getPackageFragmentRoots(ClassPathContainer.java:174)
	at org.eclipse.jdt.internal.ui.packageview.ClassPathContainer.getChildren(ClassPathContainer.java:180)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.getContainerPackageFragmentRoots(PackageExplorerContentProvider.java:363)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.getChildren(PackageExplorerContentProvider.java:300)
	at org.eclipse.jdt.internal.ui.packageview.WorkingSetAwareContentProvider.getChildren(WorkingSetAwareContentProvider.java:79)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1445)
	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:350)
	at org.eclipse.jdt.internal.ui.viewsupport.ProblemTreeViewer.hasFilteredChildren(ProblemTreeViewer.java:245)
	at org.eclipse.jdt.internal.ui.filters.EmptyLibraryContainerFilter.select(EmptyLibraryContainerFilter.java:32)
	at org.eclipse.jdt.internal.ui.viewsupport.ProblemTreeViewer.isFiltered(ProblemTreeViewer.java:295)
```

Ideally, IO can be avoided during classpath resolution. The way to trace/debug within Eclipse applications is typically logging to system out when the trace/debug flag is enabled with the `.options` file. Traditional server logging frameworks are too heavyweight in the UI thread.

**Comment by plaird** [comment]
Agreed, we need to move off of UI thread. Similar issues as reported in #371 and #191.
