### ISSUE TITLE
Importing Gerrit bazel workspace fails with IllegalThreadStateException

### ISSUE THREAD

**Issue by msohn** [salesforce/bazel-eclipse#464]
I tried to import Gerrit's bazel workspace (master branch) into Eclipse using the following steps:
- open Eclipse (Eclipse IDE for Enterprise Java and Web Developers Version: 2023-06 (4.28.0) Build id: 20230608-1333)
- install the bazel eclipse feature 2.0.0.v20230825-1210
- run bazelisk build release from a terminal
- import bazel workspace from Eclipse
This fails with the following error:
```
eclipse.buildId=4.28.0.20230608-1200
java.version=17.0.8
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_DE
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/xxxxxxx/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data /Users/xxxxxxx/eclipse-workspace/gerrit -product org.eclipse.epp.package.jee.product -keyring /Users/xxxxxxx/.eclipse_keyring

com.salesforce.bazel.eclipse.ui
Error
Sat Aug 26 21:00:56 CEST 2023
Bazel Workspace Import Failed

org.eclipse.core.runtime.CoreException: Error opening element at '/Users/xxxxxxx/src/git/gerrit': bazel info failed in workspace '/Users/xxxxxxx/src/git/gerrit': null
 Please check the bazel output and binary setup/configuration!
	at com.salesforce.bazel.eclipse.core.model.BazelElementOpenJob.open(BazelElementOpenJob.java:90)
	at com.salesforce.bazel.eclipse.core.model.BazelElement.getInfo(BazelElement.java:138)
	at com.salesforce.bazel.eclipse.core.model.BazelWorkspace.getBazelProjectView(BazelWorkspace.java:268)
	at com.salesforce.bazel.eclipse.core.model.SynchronizeProjectViewJob.runInWorkspace(SynchronizeProjectViewJob.java:516)
	at com.salesforce.bazel.eclipse.core.setup.ImportBazelWorkspaceJob.runInWorkspace(ImportBazelWorkspaceJob.java:135)
	at com.salesforce.bazel.eclipse.ui.wizards.BazelImportWizard.lambda$2(BazelImportWizard.java:81)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2382)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2402)
	at com.salesforce.bazel.eclipse.ui.wizards.BazelImportWizard.lambda$1(BazelImportWizard.java:80)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.core.runtime.CoreException: bazel info failed in workspace '/Users/xxxxxxx/src/git/gerrit': null
 Please check the bazel output and binary setup/configuration!
	at com.salesforce.bazel.eclipse.core.model.BazelWorkspaceInfo.load(BazelWorkspaceInfo.java:335)
	at com.salesforce.bazel.eclipse.core.model.BazelWorkspace.createInfo(BazelWorkspace.java:163)
	at com.salesforce.bazel.eclipse.core.model.BazelWorkspace.createInfo(BazelWorkspace.java:1)
	at com.salesforce.bazel.eclipse.core.model.BazelElementOpenJob.run(BazelElementOpenJob.java:110)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalThreadStateException
	at java.base/java.lang.ThreadGroup.addUnstarted(ThreadGroup.java:892)
	at java.base/java.lang.Thread.<init>(Thread.java:434)
	at java.base/java.lang.Thread.<init>(Thread.java:708)
	at java.base/java.lang.Thread.<init>(Thread.java:629)
	at com.salesforce.bazel.sdk.command.DefaultBazelCommandExecutor.pipe(DefaultBazelCommandExecutor.java:48)
	at com.salesforce.bazel.eclipse.ui.execution.EclipseConsoleBazelCommandExecutor.doExecuteProcess(EclipseConsoleBazelCommandExecutor.java:88)
	at com.salesforce.bazel.sdk.command.DefaultBazelCommandExecutor.execute(DefaultBazelCommandExecutor.java:178)
	at com.salesforce.bazel.eclipse.core.extensions.ExtensibleCommandExecutor.execute(ExtensibleCommandExecutor.java:44)
	at com.salesforce.bazel.eclipse.core.model.execution.BazelReadOnlyJob.run(BazelReadOnlyJob.java:49)
	... 1 more
```

See [1] for instructions how to clone the Gerrit source code.

[1] https://gerrit-review.googlesource.com/Documentation/dev-readme.html

**Comment by plaird** [comment]
OK, this message:

_bazel info failed in workspace_

suggests that there is something wrong either with the workspace or the Bazel setup. There is an assumption that Bazel is in your path:

https://github.com/salesforce/bazel-eclipse/blob/main/docs/bef/install.md#installing-bazel

That said, the Eclipse IDE functionality of this project is not in active development anymore. There is a note in the marketplace here:

https://marketplace.eclipse.org/content/bazel-eclipse-feature

The code will continue as a headless plugin as a language server implementation.

**Comment by guw** [comment]
@plaird See https://wagenknecht.org/blog/archives/2023/08/bazel-eclipse-feature-is-here.html

**Comment by guw** [comment]
@msohn Thanks for testing. I suspect something in the JDK/JRE you are using. According to the exception the ThreadGroup was destroyed, which I never saw happening (Azul OpenJDK 17).

**Comment by msohn** [comment]
Now I am confused, is the Bazel Eclipse feature alive or was it stopped ?
I read @guw's blog where he announced the availability of the Bazel Eclipse feature that's why I tried it for Gerrit development.

The workspace import didn't work since bazel wasn't on the PATH. After fixing that I can import the workspace but there are couple of build issues in Eclipse (I successfully ran a bazel build from a terminal before trying that):

- for some targets it complains there is no srcs folder, not sure what that means, these targets have their srcs defined in the BUILD file typically by a glob like `srcs = glob(["**/*.java"],)`. Adding an empty srcs folder to the respective package can silence this problem but it looks wrong to create empty srcs folders, looks like srcs is taken literally instead of using the glob defined in the BUILD file
- it looks like there is a problem with using [AutoValue](https://github.com/google/auto/tree/main/value) which is used extensively in Gerrit to generate value classes, the generated classes aren't found in Eclipse. E.g. _The type com.google.gerrit.entities.Project$NameKey cannot be resolved. It is indirectly referenced from required type com.google.gerrit.httpd.AutoValue_AdvertisedObjectsCacheKey_

**Comment by guw** [comment]
@msohn Can you give it another try with the latest updated? I found a new challenge in some Gerrit targets, which wasn't supported previously. But it now works and I get all building in Eclipse for me after importing the workspace.

AutoValue should work because Eclipse has the *jars* with the generated classes on its classpath.

**Comment by msohn** [comment]
I updated to  2.0.0.v20230829-0909 and this now looks better.

There is still a remaining issue:

It seems the target `//antlr3:query_parser` isn't recognized properly, its generating the QueryParser based on the grammar file `antlr3/com/google/gerrit/index/query/Query.g` using antlr3. The grammar file isn't shown under `srcs/` and apparently the corresponding build result `bazel-bin/antlr3/libquery_parser.jar` isn't recognized. Hence other targets/Eclipse projects using that don't build, e.g. `java.com.google.gerrit.index:index`

**Comment by plaird** [comment]
@msohn sorry for the confusion, I didn't think the Eclipse IDE part of the project was going to be supported by this renewed effort but the new announcement changes that.

**Comment by guw** [comment]
@msohn there is now support for generated sources. Can you give it a try? It's not perfect yet (doesn't handle deletions).
