### ISSUE TITLE
Missing support for java_test in project-per-target provisioning strategy

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-eclipse#475]
@guw Hi, me again! 😈  Today tried again to use this with https://github.com/enola-dev/enola (with https://github.com/enola-dev/enola/pull/285), to try if salesforce/bazel-vscode-java#49 did the trick...

It seems like it's definitely much better now, and I now see e.g. _Bazel Build Targets_ in the _Explorer_ - yay!

However it seems like it's still not entirely working; e.g. if I open the [`EmptyResourceTest.java`](https://github.com/enola-dev/enola/blob/main/common/common/src/test/java/dev/enola/common/io/resource/EmptyResourceTest.java) then the class name has a "red squiggle" in the editor, which says _Implicit super constructor Object() is undefined for default constructor. Must define an explicit constructor_ - huh? (It's not finding the JDK, perhaps?)

And the _Output_ for _Language Support for Java_ shows this error, when opening that source file:

```
[Error - 3:31:55 PM] Dec 2, 2023, 3:31:55 PM common/common/src/test/java/dev/enola/common/io/resource [in _main] does not exist
common/common/src/test/java/dev/enola/common/io/resource [in _main] does not exist
Java Model Exception: Error in Java Model (code 969): common/common/src/test/java/dev/enola/common/io/resource [in _main] does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:550)
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getUnderlyingResource(PackageFragmentRoot.java:761)
	at org.eclipse.jdt.internal.core.PackageFragment.getUnderlyingResource(PackageFragment.java:426)
	at org.eclipse.jdt.internal.core.Openable.getUnderlyingResource(Openable.java:349)
	at org.eclipse.jdt.internal.core.CompilationUnit.getUnderlyingResource(CompilationUnit.java:987)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDiagnosticsHandler.collectNonJavaProblems(BaseDiagnosticsHandler.java:149)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDiagnosticsHandler.endReporting(BaseDiagnosticsHandler.java:135)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.reportProblems(ReconcileWorkingCopyOperation.java:148)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:112)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:742)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:808)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1326)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:326)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:289)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler$PublishDiagnosticJob.run(BaseDocumentLifeCycleHandler.java:751)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

So looks like some ... "mapping" (?) is still not quite right?

**Comment by vorburger** [comment]
Oh, wow! It seems to work GREAT with `target_provisioning_strategy: project-per-package` - thank you so much!!!

PS: https://github.com/enola-dev/enola/pull/285 finally merged; and https://docs.enola.dev/dev/ide/ now updated for VSC.
