### ISSUE TITLE
Project-per-package strategy: "Missing linked source folder"

### ISSUE THREAD

**Issue by criemen** [salesforce/bazel-eclipse#491]
I tried out the `project-per-package` strategy [here](https://github.com/criemen/eclipse-repro-ppp).

As expected, I get `subproject` as eclipse project (great!), but it doesn't compile in eclipse, and I get
```
Project 'subproject' is missing required source folder: 'linked-srcs'	subproject
```
 (and the same for `linked-test-srcs`).

How can I resolve this?

If this were building, then I _believe_ the classpath setup to be too broad - currently, our project is setup with a folder with plenty of `java_import` statements, and `project-per-target` all lumps them together in a single Eclipse project. Therefore, as soon as you depend on any of those, the eclipse build will get access to all dependencies. This is incorrect, as the bazel build only has access to the specified dependencies.
I can report a separate bug for this once I can actually build the example project, though.

**Comment by guw** [comment]
We need better error handling here. Basically when the `project-per-package` strategy is being used there should *never* be a `linked-srcs` or `linked-test-srcs`. If these show up or get created into the raw classpath somehow, it's a sign of a gap in the strategy.

First thing to check is the `.log` file (Java Language Server Log file).

**Comment by criemen** [comment]
I imported this into eclipse - how can I find this log file?

**Comment by guw** [comment]
_Cmd/Ctrl+3 > Error Log_ is the fasted way from within Eclipse

**Comment by criemen** [comment]
Relevant log:

![Image](https://github.com/salesforce/bazel-eclipse/assets/70492/b0ad9317-6310-422c-9b13-c224dddeb1e6)

Double clicking on one of the exceptions yields:
```
java.lang.IllegalArgumentException: Invalid output from BuildEventStream. No longer support: []
	at com.google.idea.blaze.base.command.buildresult.OutputArtifactParser$LocalFileParser.getBlazeOutRelativePath(OutputArtifactParser.java:48)
	at com.google.idea.blaze.base.command.buildresult.OutputArtifactParser$LocalFileParser.parse(OutputArtifactParser.java:67)
	at com.google.idea.blaze.base.command.buildresult.OutputArtifactParser.parseArtifact(OutputArtifactParser.java:78)
	at com.google.idea.blaze.base.command.buildresult.ParsedBepOutput.lambda$9(ParsedBepOutput.java:321)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.google.idea.blaze.base.command.buildresult.ParsedBepOutput.parseFiles(ParsedBepOutput.java:322)
	at com.google.idea.blaze.base.command.buildresult.ParsedBepOutput.computeOutputFiles(ParsedBepOutput.java:297)
	at com.google.idea.blaze.base.command.buildresult.ParsedBepOutput.parseBepArtifacts(ParsedBepOutput.java:276)
	at com.salesforce.bazel.sdk.command.BazelBuildCommand.generateResult(BazelBuildCommand.java:54)
	at com.salesforce.bazel.sdk.command.BazelBuildCommand.generateResult(BazelBuildCommand.java:1)
	at com.salesforce.bazel.sdk.command.DefaultBazelCommandExecutor.doExecuteProcess(DefaultBazelCommandExecutor.java:180)
	at com.salesforce.bazel.sdk.command.DefaultBazelCommandExecutor.execute(DefaultBazelCommandExecutor.java:219)
	at com.salesforce.bazel.eclipse.core.extensions.ExtensibleCommandExecutor.execute(ExtensibleCommandExecutor.java:44)
	at com.salesforce.bazel.eclipse.core.model.execution.JobsBasedExecutionService.lambda$1(JobsBasedExecutionService.java:84)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2448)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2468)
	at com.salesforce.bazel.eclipse.core.model.execution.JobsBasedExecutionService.executeWithinExistingWorkspaceLock(JobsBasedExecutionService.java:78)
	at com.salesforce.bazel.eclipse.core.model.BazelElementCommandExecutor.runDirectlyWithinExistingWorkspaceLock(BazelElementCommandExecutor.java:119)
	at com.salesforce.bazel.eclipse.core.model.discovery.ProjectPerPackageProvisioningStrategy.computeClasspaths(ProjectPerPackageProvisioningStrategy.java:165)
	at com.salesforce.bazel.eclipse.core.classpath.BazelClasspathManager.updateClasspath(BazelClasspathManager.java:407)
	at com.salesforce.bazel.eclipse.core.classpath.InitializeOrRefreshClasspathJob.runInWorkspace(InitializeOrRefreshClasspathJob.java:153)
	at com.salesforce.bazel.eclipse.core.model.SynchronizeProjectViewJob.initializeClasspaths(SynchronizeProjectViewJob.java:516)
	at com.salesforce.bazel.eclipse.core.model.SynchronizeProjectViewJob.runInWorkspace(SynchronizeProjectViewJob.java:713)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Not sure how I'm supposed to interpret this. Do note that you ca reproduce this yourself using the project at https://github.com/criemen/eclipse-repro-ppp.

**Comment by guw** [comment]
I looked at it and while I have a potential fix for adding support for this, there is another limitation. The project-per-package is intended for Maven like layouts. Thus, the source code should be in a "srcs" folder but not directly in the project root.

In you sample project:
https://github.com/criemen/eclipse-repro-ppp/blob/4267a612b210b4104f388dd7e2d4fb089ee02c0d/subproject/BUILD.bazel#L1-L16

I recommend a folder structure where the Java package root is not the build file.
```
srcs = ["src/Main.java"]  --> srcs = ["srcs/src/Main.java"],
...
srcs = ["test/MainTest.java"]  --> srcs = ["srcs-test/test/MainTest.java"],
```

**Comment by guw** [comment]
@criemen closing as the project works with a little bit of restructuring
